		</div><!-- End of Middle -->

		<!-- Footer -->
		<div class="footer-wrapper">
			<footer>
				<div class="footer-menu-container">
					<ul>
						<li><a class="show-terms-and-conditions" href="javascript:void(0);">Terms &amp; Conditions</a>
						<li><a class="show-privacy-policy" href="javascript:void(0);">Privacy Policy</a>
						<li><a class="show-cancellation-policy" href="javascript:void(0);">Cancellation Policy</a>
					</ul>
				</div>
				<div class="copyright-container">
					<p>&copy; Copyright Make Reservations <?php date_default_timezone_set('UTC'); echo "" . date("Y"); ?>.</p>
				</div>
			</footer>
		</div><!-- End of Footer -->

	</div>
				<div class="pop-in-privacy-policy">
					<div class="popover-content-description">
						<div class="rate-pop">
							<div class="close-pop"><img src="images/close@2x.png">close</div>
							<h3 class="title-room-pop">PRIVACY POLICY</h3>
							<div class="rate-desc">
								<p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
							</div>
						</div>
					</div>
				</div>
                
                <div class="pop-in-terms-and-conditions">
					<div class="popover-content-description">
						<div class="rate-pop">
							<div class="close-pop"><img src="images/close@2x.png">close</div>
							<h3 class="title-room-pop">TERMS AND CONDITIONS</h3>
							<div class="rate-desc">
								<p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
							</div>
						</div>
					</div>
				</div>
                
                <div class="pop-in-cancellation-policy">
					<div class="popover-content-description">
						<div class="rate-pop">
							<div class="close-pop"><img src="images/close@2x.png">close</div>
							<h3 class="title-room-pop">CANCELLATION POLICY</h3>
							<div class="rate-desc">
								<p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
							</div>
						</div>
					</div>
				</div>

				<div class="pop-in-room-block-policy">
					<div class="popover-content-description">
						<div class="rate-pop">
							<div class="close-pop"><img src="images/close@2x.png">close</div>
							<h3 class="title-room-pop">ROOM BLOCK RESERVATION POLICY</h3>
							<div class="rate-desc">
								<p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
                                <p><span class="rate-title">Reservation Cancellation Policy:</span> 24 hour standard cancellation policy allows cancellation by 3 P.M. the day prior to arrival with no penalty. After this time, the charge would be the first nights room rate plus taxes & fees.  Your credit card will be kept on file to guarantee your reservation.</p>
								<p><span class="rate-title">Credit Card Authorizations:</span> Debit and Credit cards will be authorized at check-in for the amount of your stay, plus an amount to cover incidentals. The authorization will hold the funds until check out, at which time the amount actually incurred during the stay will be charged. Authorized amounts may take up to 30 days after departure to be released by your bank or financial institution and the hotel will not be responsible for any resulting fees or charges.</p>
								<p><span class="rate-title">For Debit Card Users:</span> Credit card authorization forms are accepted.  Please contact the hotel directly to make arrangements. Please note that your bank will automatically "freeze" your account for the amount of the estimated charges (Room and Tax for your stay +$amount per stay for incidentals). This amount will remain on hold during your stay and for a period of up to 14 days after you check out regardless if you used the debit card as a final payment. Our hotel has no control over this, as it is the bank's policy. By being made aware of these policies it will enable you to avoid possible overdrafts on your debit card. If you have any questions regarding this, please do not hesitate to contact our Manager on Duty or any Front Office Agent.</p>
								<p><span class="rate-title">Early Departure Penalty:</span> At the time of Check-in, you will be asked to confirm your departure date. You may be able to change your departure date without a penalty if your rate plan permits and if you do so before the end of your arrival day. After reconfirming your departure date, if you decide to leave earlier, you may be charged the early departure fee. Please contact the hotel if you have any questions.</p>
							</div>
						</div>
					</div>
				</div>

				<div class="pi-loader"></div>
</div>


<script src="js/jquery.flexslider.js" type="text/javascript"></script>
<script src="js/jquery-ui.min.js" type="text/javascript"></script>
<script src="js/stacktable.min.js" type="text/javascript"></script>

<script src="js/cardcheck.min.js" type="text/javascript"></script>

<script src="js/moment.js" type="text/javascript"></script>
<script src="js/scripts.js" type="text/javascript"></script>

</body>
</html>
